= FSL Community BSP for Christ Electronic Systems Devices

Yocto System requirements can be found https://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#ref-manual-system-requirements[here] and required packages for the build https://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#required-packages-for-the-build-host[here]

For an Ubuntu Build Host you need the following packages:

[source,console]
$: sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib g++-multilib \
build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev \
pylint3 xterm

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir ces-bsp-platform
$: cd ces-bsp-platform
$: repo init -u https://github.com/software-celo/ces-bsp-platform -b dunfell
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To create a new Yocto build directory:

[source,console]
$: MACHINE=pixi-cdl100 DISTRO=ces-fb source ./setup-environment build

Refer here for https://github.com/software-celo/meta-ces/tree/dunfell[supported MACHINES]

Christ currently maintains one distro (ces-fb)

* ces-fb is used for qt/eglfs based images (ces-qt-demoimage)

> When upgrading or switching between rocko and warrior or dunfell images make sure to use the
> corresponding version of CURT and always update the U-Boot as well.
> Please do NOT mix rocko/warrior U-Boot and devicetrees! These are incompatible and will
> definitely break your system until you deploy a complete update.
> warrior and dunfell are completely compatible concerning CURT.
> Refer to our https://www.christ-es.com/index.php?id=650[FAQ] as well.

To use an existing Yocto build directory:

[source,console]
source ./setup-environment build

To start a simple image build:

[source,console]
$: bitbake ces-qt-demoimage

You can use any directory to host your build.

The source code is checked out at `ces-bsp-platform/sources`.

> When building the ces-qt-demoimage at least 16GB RAM are recommended. It should work with less, but it might fail if e.g. two big packages are compiled at the same time. Try to build again (maybe multiple times), use `bitbake -k` or increase your SWAP parition.

Depending on your system performance, the build process can take several hours. The image will be located in:
tmp-glibc/deploy/images/$MACHINE/

For further information refer to the http://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html[Yocto Project Reference Manual].
