= FSL Community BSP for Christ Electronic Systems Devices

Yocto System requirements can be found http://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#intro-requirements[here]

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir ces-bsp-platform
$: cd ces-bsp-platform
$: repo init -u https://github.com/software-celo/ces-bsp-platform -b warrior
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To create a new Yocto build directory:

[source,console]
$: MACHINE=pixi-cdl100 DISTRO=ces-fb source ./setup-environment build

Refer here for https://github.com/software-celo/meta-ces/tree/warrior[supported MACHINES]

Christ currently maintains one distro (ces-fb)

* ces-fb is used for qt/eglfs based images (ces-qt-demoimage)

Christ currently included this distro (ces-x11) , but will be removed in the future

* ces-x11 is used for x11 based images (ces-chromium-demoimage)

> Please pay attention when upgrading from the old naming scheme (crixq/pixidl).
> The devicetree name was also changed, so be sure to upgrade the
> u-boot environment or the whole bootloader along with your image!

> Before upgrading to yocto 2.7 (warrior), please contact us (linux@christ-es.de) for
> a special version of CURT, which is able to migrate your system properly. Please
> do NOT mix rocko/warrior U-Boot and devicetrees! These are incompatible and will
> definitely break your systems until you deploy a complete update.

To use an existing Yocto build directory:

[source,console]
source ./setup-environment build

To start a simple image build:

[source,console]
$: bitbake ces-qt-demoimage

You can use any directory to host your build.

The source code is checked out at `ces-bsp-platform/sources`.

> In order to build the ces-chromium-demoimage you need a powerful machine.
> The chromium recipe says: "The linker step requires at least 16 GB RAM." Or turn
> on the component-build PACKAGECONFIG.
> An increasement of the SWAP partition could be helpful in some cases.

For further information refer to the http://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html[Yocto Project Reference Manual].
