= FSL Community BSP for Christ Electronic Systems Devices

Yocto System requirements can be found http://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#intro-requirements[here]

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir ces-bsp-platform
$: cd ces-bsp-platform
$: repo init -u https://github.com/software-celo/ces-bsp-platform -b morty
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To create a new Yocto build directory:

[source,console]
$: MACHINE=pixi-cdl100 DISTRO=poky source ./setup-environment build

(Available machines are for example: pixi-cdl100, crix-cq100, crix-arq100)

> Please pay attention when upgrading from the old naming scheme (crixq/pixidl).
> The devicetree name was also changed, so be sure to upgrade the
> u-boot environment or the whole bootloader along with your image!

To use an existing Yocto build directory:

[source,console]
source ./setup-environment build

To start a simple image build:

[source,console]
$: bitbake ces-qt-demoimage

You can use any directory to host your build.

The source code is checked out at `ces-bsp-platform/sources`.

For further information refer to the http://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html[Yocto Project Reference Manual].
