= FSL Community BSP for Christ Electronic Systems Devices

Yocto System requirements can be found https://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#ref-manual-system-requirements[here].

For an Ubuntu 16.04 Build Host you need the packages specified https://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#required-packages-for-the-build-host[here].

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir ces-bsp-platform
$: cd ces-bsp-platform
$: repo init -u https://github.com/software-celo/ces-bsp-platform -b warrior
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To create a new Yocto build directory:

[source,console]
$: MACHINE=pixi-cdl100 DISTRO=ces-fb source ./setup-environment build

Refer here for https://github.com/software-celo/meta-ces/tree/warrior[supported MACHINES]

Christ currently maintains one distro (ces-fb)

* ces-fb is used for qt/eglfs based images (ces-qt-demoimage)

Christ currently included this distro (ces-x11) , but will be removed in the future

* ces-x11 is used for x11 based images (ces-chromium-demoimage)

> When upgrading or switching between rocko and warrior images make sure to use the
> corresponding version of CURT and always update the U-Boot as well.
> Please do NOT mix rocko/warrior U-Boot and devicetrees! These are incompatible and will
> definitely break your system until you deploy a complete update.
> Refer to our https://www.christ-es.com/index.php?id=650[FAQ] as well.

To use an existing Yocto build directory:

[source,console]
source ./setup-environment build

If using a fresh docker image, your locale might not be set to en_US.UTF8.
Follow the instructions https://github.com/RobertBerger/meta-mainline/issues/8[here] to set it, otherwise your build will error.

The build should be started as a normal user and NOT as a superuser. The coreutils build will error otherwise.
If you're building from a docker image, you're logged-in as a superuser by default. Create a new user and switch to it before starting the build.
Finally, to start a simple image build:

[source,console]
$: bitbake ces-qt-demoimage

You can use any directory to host your build.

The source code is checked out at `ces-bsp-platform/sources`.

> In order to build the ces-chromium-demoimage you need a powerful machine.
> The chromium recipe says: "The linker step requires at least 16 GB RAM." Or turn
> on the component-build PACKAGECONFIG.
> An increasement of the SWAP partition could be helpful in some cases.

Depending on your system performance, the build process can take several hours. The image will be located in:
tmp-glibc/deploy/images/$MACHINE/

For further information refer to the http://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html[Yocto Project Reference Manual].
